import os
import google.generativeai as genai
from github import Github

# API and GitHub Configuration
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GITHUB_TOKEN = os.getenv("GH_TOKEN")
REPO_NAME = os.getenv("GITHUB_REPOSITORY")

genai.configure(api_key=GEMINI_API_KEY)
g = Github(GITHUB_TOKEN)
repo = g.get_repo(REPO_NAME)

BLOG_FOLDER = "Blog-posts"

def get_existing_data():
    """Fetches existing blog topics and format sample."""
    topics = []
    sample_format = ""
    try:
        contents = repo.get_contents(BLOG_FOLDER)
        files = [f for f in contents if f.type == "file" and f.name.endswith(".md")]
        topics = [f.name.replace(".md", "").lower() for f in files]
        
        if files:
            sample_file = repo.get_contents(files[0].path)
            sample_format = sample_file.decoded_content.decode('utf-8')
            
        return topics, sample_format
    except Exception as e:
        print(f"Notice: {e}")
        return topics, sample_format

def get_repository_tools():
    try:
        contents = repo.get_contents("")
        tools = [c.name for c in contents if c.type == "file" and not c.name.startswith('.')]
        return ", ".join(tools)
    except Exception:
        return "Various open-source tech tools and scripts"

def generate_blog_content(existing_blogs, tools_info, sample_format):
    """Generates a 1500+ word educational tech guide."""
    # Using Gemini 1.5 Pro for long-form, high-quality content
    model = genai.GenerativeModel('gemini-1.5-pro')
    
    prompt = f"""
    You are an expert open-source contributor, educator, and tech blogger. 
    Our repository contains these tools/files: {tools_info}.
    Topics already covered (DO NOT write about these): {existing_blogs}.
    
    CRITICAL FORMATTING INSTRUCTION:
    If available, follow this exact formatting style:
    ---
    {sample_format}
    ---
    
    Task Instructions:
    1. Pick a UNIQUE, highly engaging tech topic related to our repository tools.
    2. Write a comprehensive, step-by-step educational tech guide. 
    3. MANDATORY LENGTH: The blog post MUST be a minimum of 1500 words. Dive deep into technical details, provide code snippets (if applicable), and explain the architecture or logic.
    4. TONE: "Open-source style" - make it highly informative, transparent, and encouraging so that ANYONE (from beginners to advanced users) can learn how things work under the hood. Use a human-touch, conversational yet professional voice.
    5. At the end, include a "Working Need FAQ" section (practical usage, real-life problem solving, troubleshooting).
    6. At the very top of your response, provide the filename exactly like this: 'FILENAME: your-topic-slug.md' followed by a newline, then the actual Markdown content.
    """
    
    response = model.generate_content(prompt)
    return response.text

def save_blog_to_github(generated_text):
    if "FILENAME:" not in generated_text:
        print("Error: Invalid format generated by AI.")
        return False

    parts = generated_text.split("\n", 1)
    title_slug = parts[0].replace("FILENAME:", "").strip()
    blog_content = parts[1].strip()
    
    if not title_slug.endswith(".md"):
        title_slug += ".md"
        
    file_path = f"{BLOG_FOLDER}/{title_slug}"
    
    try:
        repo.create_file(
            path=file_path,
            message=f"Feat: Added detailed educational tech guide - {title_slug}",
            content=blog_content,
            branch="main" 
        )
        print(f"Success: Uploaded huge tech guide -> {file_path}")
        return True
    except Exception as e:
        print(f"Error saving file {file_path}: {e}")
        return False

if __name__ == "__main__":
    print("Starting Automated High-Quality Tech Guide Generation...")
    
    existing_topics, format_template = get_existing_data()
    tools = get_repository_tools()
    
    # We only generate ONE high-quality 1500+ word blog per run.
    # Since the GitHub Action is scheduled 3 times a day, we will get 3 blogs daily.
    blog_text = generate_blog_content(existing_topics, tools, format_template)
    save_blog_to_github(blog_text)
    
    print("Process Completed Successfully.")
